
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 18 14:57:51 BOT 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 5;
  public static final int Exponenciacion = 26;
  public static final int Arreglo = 15;
  public static final int For = 7;
  public static final int LlaveAbierto = 13;
  public static final int Suma = 23;
  public static final int OP_Mayor = 17;
  public static final int Numero = 32;
  public static final int OP_Igualdad = 16;
  public static final int ParentesisAbierto = 11;
  public static final int Float = 3;
  public static final int Imprimir = 9;
  public static final int Identificador = 31;
  public static final int Int = 2;
  public static final int LlaveCerrado = 14;
  public static final int Else_If = 6;
  public static final int Main = 29;
  public static final int Cadena = 33;
  public static final int ParentesisCerrado = 12;
  public static final int EOF = 0;
  public static final int NumeroDecimal = 30;
  public static final int Division = 27;
  public static final int OP_MayorOIgual = 19;
  public static final int OP_NoIgual = 21;
  public static final int OP_Menor = 18;
  public static final int Resta = 24;
  public static final int If = 4;
  public static final int Linea = 10;
  public static final int error = 1;
  public static final int Modulo = 28;
  public static final int Igual = 22;
  public static final int Multiplicacion = 25;
  public static final int While = 8;
  public static final int OP_MenorOIgual = 20;
  public static final int Error = 34;
}

